services:
    database:
        container_name: postgres_container
        image: postgres:17-bookworm
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - postgre-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 5s
            timeout: 5s
            retries: 10

    database-admin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
        ports:
            - "8081:8081"
        networks:
            - app-network
        depends_on:
            - database

    redis: 
        container_name: redis
        image: redis:latest
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/var/lib/redis/data
        networks:
            - app-network

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASSWORD: guest  
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - rabbitmq-data:/var/lib/rabbitmq/data
        networks:
            - app-network

    backend:
        build: 
            context: /backend
            dockerfile: Dockerfile
        command: uv run uvicorn main:app --reload --host=0.0.0.0 --port=8000 --log-level='trace'
        restart: unless-stopped
        environment:
            DB_NAME: ${POSTGRES_DB}
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            OLLAMA_ENDPOINT: ${OLLAMA_ENDPOINT}
        volumes:
            - ./common:/backend/common
        ports:
            - "8000:8000"
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: .
                  target: /backend
                  ignore: 
                    - .venv/
                    - .git/
                    - __pycache__/
                
                - action: rebuild
                  path: ./uv.lock
        env_file:
            - .env
        depends_on:
            - database
            - redis
            - ollama
    
    ollama-service:
        container_name: ollama_service
        build:
            context: /ollama_service
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./common:/ollama_service/common
        ports:
            - "8001:8001"
        networks:
            - app-network
        


    # llm-distributor:
    #     <<: *backend
    #     command: uv run ./distributors/llm_model/main.py
    #     ports:
    #         - "8001:8001"
    #     volumes:
    #         - common-data:/backend

    telegram-bot:
        build: 
            context: /bot
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            TOKEN: ${TELEGRAM_TOKEN}
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_NAME: ${POSTGRES_DB}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
        volumes:
            - ./common:/bot/common
        ports: 
            - "8080:8080"
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: .
                  target: /bot
                  ignore: 
                    - .venv/
                    - .git/
                    - __pycache__/
                
                - action: rebuild
                  path: ./uv.lock
        env_file:
            - .env
        depends_on:
            - database

    ollama:
        image: ollama/ollama:latest
        restart: unless-stopped
        pull_policy: always
        tty: true
        environment:
            OLLAMA_MODELS: /usr/lib/ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama-data:/usr/lib/ollama
        deploy:
            resources:
              reservations:
                devices:
                  - driver: nvidia
                    capabilities: [gpu]
        networks:
            - app-network
                

volumes:
    postgre-data:
    ollama-data:
    redis-data:
    common-data:
    rabbitmq-data:

networks:
    app-network:
        driver: bridge 
