services:
    database:
        container_name: postgres_container
        image: postgres:17-bookworm
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - postgre-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - ai-network
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 5s
            timeout: 5s
            retries: 10

    backend:
        build: 
            context: /backend
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            DB_NAME: ${POSTGRES_DB}
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "8000:8000"
        networks:
            - ai-network
        develop:
            watch:
                - action: sync
                  path: .
                  target: /backend
                  ignore: 
                    - .venv/
                
                - action: rebuild
                  path: ./uv.lock
        env_file:
            - .env
        depends_on:
            - database
            - ollama
    
    telegram-bot:
        build: 
            context: /bot
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            TOKEN: ${TELEGRAM_TOKEN}
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
        ports: 
            - "8080:8080"
        networks:
            - ai-network
        develop:
            watch:
                - action: sync
                  path: .
                  target: /bot
                  ignore: 
                    - .venv/
                
                - action: rebuild
                  path: ./uv.lock
        env_file:
            - .env
        depends_on:
            - database

    ollama:
        image: ollama/ollama:latest
        restart: unless-stopped
        ports:
            - "11434:11434"
        volumes:
            - ollama-data:/var/lib/ollama/data
        deploy:
            resources:
              reservations:
                devices:
                  - driver: nvidia
                    capabilities: [gpu]
        networks:
            - ai-network
                

volumes:
    postgre-data:
    ollama-data:

networks:
    ai-network:
        driver: bridge
