[project]
name = "ollama-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "asyncio>=3.4.3",
    "asyncpg>=0.30.0",
    "ollama>=0.5.1",
    "sqlalchemy>=2.0.41",
    "redis>=6.2.0",
]
