[project]
name = "ollama-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "asyncio>=3.4.3",
    "ollama>=0.5.1",
    "faststream>=0.5.45",
    "aiohttp>=3.12.13",
]
